/* oxlint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as deviceRouteRouteImport } from './routes/(device)/route'
import { Route as platformRouteRouteImport } from './routes/(platform)/route'
import { Route as managerManagerRouteImport } from './routes/(manager)/manager'
import { Route as screenScreenRouteImport } from './routes/(screen)/screen'
import { Route as settingsSettingsRouteImport } from './routes/(settings)/settings'
import { Route as devicePairIndexRouteImport } from './routes/(device)/pair/index'
import { Route as platformTabIndexRouteImport } from './routes/(platform)/$tab/index'
import { Route as platformDebugIndexRouteImport } from './routes/(platform)/debug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const deviceRouteRoute = deviceRouteRouteImport.update({
  id: '/(device)',
  getParentRoute: () => rootRouteImport,
} as any)
const platformRouteRoute = platformRouteRouteImport.update({
  id: '/(platform)',
  getParentRoute: () => rootRouteImport,
} as any)
const managerManagerRoute = managerManagerRouteImport.update({
  id: '/(manager)/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const screenScreenRoute = screenScreenRouteImport.update({
  id: '/(screen)/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsSettingsRoute = settingsSettingsRouteImport.update({
  id: '/(settings)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const devicePairIndexRoute = devicePairIndexRouteImport.update({
  id: '/pair/',
  path: '/pair/',
  getParentRoute: () => deviceRouteRoute,
} as any)
const platformTabIndexRoute = platformTabIndexRouteImport.update({
  id: '/$tab/',
  path: '/$tab/',
  getParentRoute: () => platformRouteRoute,
} as any)
const platformDebugIndexRoute = platformDebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => platformRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof managerManagerRoute
  '/screen': typeof screenScreenRoute
  '/settings': typeof settingsSettingsRoute
  '/pair/': typeof devicePairIndexRoute
  '/$tab/': typeof platformTabIndexRoute
  '/debug/': typeof platformDebugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager': typeof managerManagerRoute
  '/screen': typeof screenScreenRoute
  '/settings': typeof settingsSettingsRoute
  '/pair': typeof devicePairIndexRoute
  '/$tab': typeof platformTabIndexRoute
  '/debug': typeof platformDebugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(device)': typeof deviceRouteRouteWithChildren
  '/(platform)': typeof platformRouteRouteWithChildren
  '/(manager)/manager': typeof managerManagerRoute
  '/(screen)/screen': typeof screenScreenRoute
  '/(settings)/settings': typeof settingsSettingsRoute
  '/(device)/pair/': typeof devicePairIndexRoute
  '/(platform)/$tab/': typeof platformTabIndexRoute
  '/(platform)/debug/': typeof platformDebugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/manager' | '/screen' | '/settings' | '/pair/' | '/$tab/' | '/debug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manager' | '/screen' | '/settings' | '/pair' | '/$tab' | '/debug'
  id:
    | '__root__'
    | '/'
    | '/(device)'
    | '/(platform)'
    | '/(manager)/manager'
    | '/(screen)/screen'
    | '/(settings)/settings'
    | '/(device)/pair/'
    | '/(platform)/$tab/'
    | '/(platform)/debug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  deviceRouteRoute: typeof deviceRouteRouteWithChildren
  platformRouteRoute: typeof platformRouteRouteWithChildren
  managerManagerRoute: typeof managerManagerRoute
  screenScreenRoute: typeof screenScreenRoute
  settingsSettingsRoute: typeof settingsSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(device)': {
      id: '/(device)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof deviceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(platform)': {
      id: '/(platform)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof platformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(manager)/manager': {
      id: '/(manager)/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof managerManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(screen)/screen': {
      id: '/(screen)/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof screenScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(settings)/settings': {
      id: '/(settings)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof settingsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(device)/pair/': {
      id: '/(device)/pair/'
      path: '/pair'
      fullPath: '/pair/'
      preLoaderRoute: typeof devicePairIndexRouteImport
      parentRoute: typeof deviceRouteRoute
    }
    '/(platform)/$tab/': {
      id: '/(platform)/$tab/'
      path: '/$tab'
      fullPath: '/$tab/'
      preLoaderRoute: typeof platformTabIndexRouteImport
      parentRoute: typeof platformRouteRoute
    }
    '/(platform)/debug/': {
      id: '/(platform)/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof platformDebugIndexRouteImport
      parentRoute: typeof platformRouteRoute
    }
  }
}

interface deviceRouteRouteChildren {
  devicePairIndexRoute: typeof devicePairIndexRoute
}

const deviceRouteRouteChildren: deviceRouteRouteChildren = {
  devicePairIndexRoute: devicePairIndexRoute,
}

const deviceRouteRouteWithChildren = deviceRouteRoute._addFileChildren(
  deviceRouteRouteChildren,
)

interface platformRouteRouteChildren {
  platformTabIndexRoute: typeof platformTabIndexRoute
  platformDebugIndexRoute: typeof platformDebugIndexRoute
}

const platformRouteRouteChildren: platformRouteRouteChildren = {
  platformTabIndexRoute: platformTabIndexRoute,
  platformDebugIndexRoute: platformDebugIndexRoute,
}

const platformRouteRouteWithChildren = platformRouteRoute._addFileChildren(
  platformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  deviceRouteRoute: deviceRouteRouteWithChildren,
  platformRouteRoute: platformRouteRouteWithChildren,
  managerManagerRoute: managerManagerRoute,
  screenScreenRoute: screenScreenRoute,
  settingsSettingsRoute: settingsSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
